version: "3.3"
services:

  myserver:
    image: davidcontainer.azurecr.io/twitter_server:latest
    container_name: myserver
    platform: "darwin/amd64"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    build:
      context: ./
      dockerfile: server/Dockerfile

    ports:
      - 9095
    env_file:
      - ./.env
    networks:
      - mynetwork

  myclient:
    platform: "linux/amd64"
    image: davidcontainer.azurecr.io/twitter_client:latest
    container_name: myclient
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    build:
      context: ./
      dockerfile: client/Dockerfile

    env_file:
      - ./.env

    networks:
      - mynetwork

    # volumes:
    #   - /etc/localtime:/etc/localtime:ro
    depends_on:
      - myserver

networks:
  mynetwork:
    driver: bridge